name: CI/CD Pipeline

on:
  push:
    branches:
      - lab7
  pull_request:
    branches:
      - lab7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'  # Ensure compatibility with Dart SDK requirements
          channel: stable
          architecture: x64
          cache: true  # Enable caching for faster builds
          pub-cache-path: default

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test test/widget_test.dart

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: stable
          architecture: x64
          cache: true
          pub-cache-path: default

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: stable
          architecture: x64
          cache: true
          pub-cache-path: default

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
